run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocyclo
    - revive

linters-settings:
  gocyclo:
    min-complexity: 25
  revive:
    rules:
      - name: exported
        disabled: true
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - paramTypeCombine
      - octalLiteral
      - unnamedResult
      - nestingReduce
      - exitAfterDefer
      - ifElseChain

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - revive